### ISSUE TITLE
Adapting brainbox for functional programming

### ISSUE THREAD

**Issue by ranjitha** [freegroup/brainbox#11]
Hello! I love the thorough documentation! I have just started learning programming and I think it'll be pretty cool to have something like the brainbox simulator for general functions, say for eg., a function that takes a string and an integer and returns a string. It'd be fun to play around with basic programming blocks in a visual manner.

It would be really nice if you could give me a few pointers to adopt and modify the brainbox code.

**Comment by freegroup** [comment]
Hi, in general there is no need to change the code to use it as functional programming environment.

Download and install the simulator to create your own shapes.

The key feature is the "designer" for the shapes. You can draw shapes and add your javascript 
as logic. It doesn't matter if you calculate just with true/false values like I do in my demo or if you pass strings or numbers.

I can create a simple demo object if required.

**Comment by freegroup** [comment]
<img width="861" alt="Bildschirmfoto 2020-04-23 um 23 19 34" src="https://user-images.githubusercontent.com/1155039/80150609-f8086d80-85b8-11ea-8c43-1a3dea9a7f16.png">


the code to concatenate the two input values and write it to the output
https://github.com/freegroup/brainbox.shapes/blob/master/shapes/functional/text/concatenate.custom

**Comment by ranjitha** [comment]
This is perfect! Thank you so much!
