### ISSUE TITLE
Incorrect Symbol for OR-Gate

### ISSUE THREAD

**Issue by he-so** [freegroup/brainbox#2]
The shape for the OR-Gate is not following the IEC 60617-12 : 1997 standard. Please see https://de.wikipedia.org/wiki/Logikgatter#/media/Datei:IEC_OR_label.svg for reference. Its a greater or equal than and not a greater than.

**Comment by freegroup** [comment]
fixed....sorry for the delay. The complete project has restarted.

<img width="414" alt="Bildschirmfoto 2020-04-10 um 00 56 45" src="https://user-images.githubusercontent.com/1155039/78947640-39335480-7ac6-11ea-92e1-167cb40be113.png">
